### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by nicoonline** [ShaneMcC/phprouter#10]
What i'm doing wrong?
Doing a simple connection with a simple test 
Parse error: syntax error, unexpected '[' in ...phprouter-master/impl/NetworkDevice.php on line 64

**Comment by ShaneMcC** [comment]
Hi,

Sounds like you're using an old version of PHP. The code uses some features only available in PHP 7.

PHP 5 has been EOL since Dec 31st 2018.

It could probably be made to work by changing instances where I've used the [ ] syntax for arrays to be array() but I'd recommend upgrading to php 7.

**Comment by nicoonline** [comment]
I have modified the code with arrays. Now i have this :

Parse error: syntax error, unexpected T_STRING in CiscoTrait.php on line 5

**Comment by ShaneMcC** [comment]
That error suggests you're using a version older than PHP 5.4 as it's not supporting `trait`s which were introduced in 5.4 (https://www.php.net/manual/en/language.oop5.traits.php).

PHP 5.3 was EOL 6 years ago - August 2014. (https://www.php.net/eol.php)

I'm afraid I'm not going to offer too much support for PHP 5, it's EOL a long time and you really should be updating. Using newer PHP features was an intentional choice.

Supported Versions: https://www.php.net/supported-versions.php

**Comment by nicoonline** [comment]
Thanks Shane for your support. We will take the appropriate actions :)
