### ISSUE TITLE
Commands that change the prompt cause exec() hang

### ISSUE THREAD

**Issue by nicoonline** [ShaneMcC/phprouter#12]
Hello,

Trying to go live and executing a bunch of commands like this 👍 

$router = new CiscoRouter...
$result = $router->exec("$vrfcommand");
echo $result;
echo "blablaba";

===> OK
$result = $router->exec("conf t");
$result = $router->exec("router bgp 0000");

the following is not working .... and no errors ?

**Comment by nicoonline** [comment]
i set debug and seems he's waiting something..

--- 0 [FALSE] {IX(confi} == {CORE_IX#}
--- 0 [FALSE] {X(config} == {CORE_IX#}
--- 0 [FALSE] {(config)} == {CORE_IX#}
--- 0 [FALSE] {config)#} == {CORE_IX#}

**Comment by ShaneMcC** [comment]
Hi,

Yeah it doesn't understand the prompt changing from `CORE_IX#` to `CORE_IX(config)#`

I've not come up with a good/universal way of solving that yet that I want to put into the code (similar to #11) yet but what I use for my some of my own stuff is something like:

```php
// Value that won't do anything that we can write to know this is definitely us and not something the router would output normally.
$canary = '! canary-' . md5(uniqid(true));
$router->writeln($canary);
// Grab up to the canary before our actual input.
$router->getStreamData($canary . "\n");

// Code to actually do what we want
$router->writeln('conf t');
$router->writeln('router bgp 12345');
// ...
$router->writeln('end');

// Now write the canary again
$router->writeln($canary);
// and read all the output up to that point.
$result = $router->getStreamData($canary . "\n") . "\n";
$router->getStreamData();
```

This works by avoiding the internal code that tries to handle the prompt and dealing with it somewhat prompt-agnostic.

**Comment by nicoonline** [comment]
so to understand correctly, your code is working only for one command ?

**Comment by nicoonline** [comment]
i get now a :
Catchable fatal error: Object of class CiscoRouter could not be converted to string in  on line 31

**Comment by ShaneMcC** [comment]
> so to understand correctly, your code is working only for one command or commands not going to "conf t"

It works for anything that doesn't change the prompt. My original use was grabbing specific data from `show` commands on the devices and editing config on devices that didn't change the prompt.

Changing config on cisco devices was something I started using it for much later, but haven't yet added support fo in a "nice" device-agnostic way (Beyond exposing the `writeln()` and `getStreamData()` functions) though I am aware of it - alas due to the workaround above which let me do everything I've needed, it hasn't been high on my priorities list beyond "I should do something about that at some point" and other projects/work comes ahead of it.

In reality, I need to tidy up a lot of the internals of this at some point as it was rather quickly hacked together over the years.


> Catchable fatal error: Object of class CiscoRouter could not be converted to string in on line 31
I'd need to know which file it was erroring on if it was one of mine, or see what line of code you have around line 31 (ie 29 - 32) to advise further.

**Comment by ShaneMcC** [comment]
You can avoid the `$canary` stuff and just use `writeln()` and `getNextStreamData()` as per https://github.com/ShaneMcC/phprouter/wiki/Example-Usage---Reading-and-Writing-Data

Depends how much commands your're doing and how much you want the output data (eg you write the canary each time you want to grab output data - I do this to show progress as things are happening)

**Comment by nicoonline** [comment]
the issue is when i put an echo in my script 👍 

$router = new CiscoRouter($router, 'xxxxxx', 'xxHA');
echo "connecting to $router";

**Comment by nicoonline** [comment]
i found the error for Catchable fatal error. Will try to follow your advices about the Exemple usage.

**Comment by nicoonline** [comment]
Also i found a case where a show command didn't produce any output so it returns to the prompt and hang. Is there a way to set a timeout  and continue the script ?

**Comment by ShaneMcC** [comment]
If it returns you to a regular prompt it should behave. What command is it?
