### ISSUE TITLE
show ipv6

### ISSUE THREAD

**Issue by nicoonline** [ShaneMcC/phprouter#13]
When connecting to a Cisco  after the term length 👍 

-------------------------------
show ipv6
----------
% Incomplete command.
-------------------------------

**Comment by ShaneMcC** [comment]
This is an intentional check that is run.

Some devices have a bug where after logging in it puts you into a weird global `routing-context` mode that isn't able to run a whole bunch of commands (of which `show ipv6` is one of the easier ones to test against)

If this command returns "Invalid input detected" we run `routing-context vrf global` to fix it, otherwise everything is fine.
