### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by imatrycode** [ShaneMcC/phprouter#15]
Hello,

I had an issue here where everytime I ran this i got a segmentation fault not really much info without debugging.
I managed to sort it so i know its not an issue but hopefully might help someone else.

## fix
in this file i noticed is where you use sshv2

phprouter/sockets/SSHSocket.php

I changed the terminal type to:

/** TermType */
                private $termType = 'vty';

(didn't do anything)

I then changed the array for ENV (Which I saw was an empty array anyway) to NULL

 /** Env */
                private $env = NULL;

Which is what I have always set when using sshv2 normally without your classes.

This then worked.

Feel free to close the issue straight away just thought it might help someone I am using Debian 10 with PHP version 7.4 (I also started on 7.3 and upgraded just to see if it was this.

Cool scripts by the way.

## Seg fault from /var/log/syslog
Oct  5 13:15:46 LS-SAL-NOC01 kernel: [504485.568672] php[27514]: segfault at 563                                              b95165fc4 ip 0000563b94f950f1 sp 00007fff06f4f8e8 error 7 in php7.3[563b94db5000                                              +261000]
Oct  5 13:15:46 LS-SAL-NOC01 kernel: [504485.568680] Code: 48 8b 47 10 80 78 08                                               00 75 2c 48 83 c0 28 31 d2 eb 11 0f 1f 80 00 00 00 00 48 83 c0 20 80 78 e0 00 75                                               0e 83 c2 01 39 ca 75 ef <89> 0e c3 0f 1f 40 00 89 d1 89 0e c3 31 c9 eb f0 66 66                                               2e 0f 1f 84

**Comment by ShaneMcC** [comment]
Interesting, thanks.

I remember originally setting this to `null` (as that's what the default is according to https://www.php.net/manual/en/function.ssh2-shell.php) but encountering some issues with it in some situations (that I can't quite recall now). I'll have to have a look again at some point to see if I can figure it out. I think it was something to do with the underlying library not allowing you to set the width/height if you had a null env not an empty one as it was considering that parameter to not be there and counting wrong.

Later versions of the code (since 23b59c6499c74cbf8f769b7680395ec9d6ff2152) if you don't make any changes to the settings (with `setTermType`, `setEnv`, `setWidth`, or `setHeight`) will just use `ssh2_shell` without any parameters at all which probably also fixes your issue.
